theme               = "catppuccin_mocha"


## insert mode - bindings ##########################################################################
## <S-tab>          = use smart tab -> https://docs.helix-editor.com/editor.html#editorsmart-tab-section
## <C-[>            = to come to normal, makes lot of sense if you have replaced capslock with ctrl
## <C-f>            = macOS keybinding to move right in insert mode
## <C-b>            = macOS keybinding to move left in insert mode
## <C-n>            = macOS keybinding to move down in insert mode
## <C-p>            = macOS keybinding to move up in insert mode
## <disable>        = up / down / right / left / pageup / page down / home / end
####################################################################################################
[keys.insert]
"S-tab"             = "move_parent_node_start"
"C-["               = "normal_mode"
"C-f"               = ["normal_mode", "move_char_right", "insert_mode"]
"C-b"               = ["normal_mode", "move_char_left",  "insert_mode"]
"C-n"               = ["normal_mode", "move_visual_line_down", "insert_mode"]
"C-p"               = ["normal_mode", "move_visual_line_up", "insert_mode"]
"up"                = "no_op"
"down"              = "no_op"
"left"              = "no_op"
"right"             = "no_op"
"pageup"            = "no_op"
"pagedown"          = "no_op"
"home"              = "no_op"
"end"               = "no_op"


## select mode - bindings ##########################################################################
## <tab> & <S-tab>  = use smart tab -> https://docs.helix-editor.com/editor.html#editorsmart-tab-section
## "~" / <A-`>      = to switch to uppercase / to switch case, reversed the default bahavior / kakoune's keybindings are more natural
## <C-g>            = Alternative to <A-.>, easier to do, all on home row, just left fingers
## x                = more versatile (x), it can now extend in both direction depending on anchor position, do a <A-;> to flip anchor / cursor and then (x),
##                    to start extending in other direction
####################################################################################################
[keys.select]
"tab"               = "extend_parent_node_end"
"S-tab"             = "extend_parent_node_start"
"~"                 = "switch_to_uppercase"
"A-`"               = "switch_case"
"C-g"               = "repeat_last_motion"
"x"                 = "extend_line"

## select-space mode - bindings ####################################################################
## u                = to switch to lower case, available in select mode as well.
## U                = to switch to upper case, available in select mode as well.
####################################################################################################
[keys.select.space]
"u"                 = "switch_to_lowercase"
"U"                 = "switch_to_uppercase"


## normal mode - bindings ##########################################################################
## <tab> & <S-tab>  = use smart tab -> https://docs.helix-editor.com/editor.html#editorsmart-tab-section
## "C-c"            = <<space>-c> does the job well, freeing the keybinding for a better use in future
## "C-ret"          = insert new line and go into insert mode
## x                = more versatile (x), it can now extend in both direction depending on anchor position, do a <A-;> to flip anchor / cursor and then (x),
##                    to start extending in other direction
## X                = will unselect the line(s) upwards if selected by previous (x) command, else will extend upwards
## <A-x>            = will unselect the line(s) downwards if selected by previous reversed (x) command, else will extend downwards
## "~" / <A-`>      = to switch to uppercase / to switch case, reversed the default bahavior / kakoune's keybindings are more natural
## <C-g>            = Alternative to <A-.>, easier to do, all on home row, just left fingers
## <esc>            = also used to collapse selection
####################################################################################################
[keys.normal]
"tab"               = "move_parent_node_end"
"S-tab"             = "move_parent_node_start"
"C-c"               = "no_op"
"C-ret"             = ["insert_newline", "insert_mode"]
"x"                 = "extend_line"
"X"                 = ["extend_line_up", "extend_to_line_bounds"]
"A-x"               = ["extend_line_down", "extend_to_line_bounds"]
"~"                 = "switch_to_uppercase"
"A-`"               = "switch_case"
"C-g"               = "repeat_last_motion"
esc                 = ["collapse_selection"]

## normal-space mode - bindings ####################################################################
## u                = to switch to lower case, available in select mode as well.
## U                = to switch to upper case, available in select mode as well.
## q                = to close the current buffer
## q                = to force close the current buffer
## n                = to open a new scratch buffer
####################################################################################################
[keys.normal.space]
"u"                 = "switch_to_lowercase"
"U"                 = "switch_to_uppercase"
"q"                 = ":buffer-close"
"Q"                 = ":buffer-close!"
"n"                 = ":vsplit-new"

## (new) normal-G mode - bindings ##################################################################
## to move around and extend selection, "G" == ";vg" ###############################################
## l                = to select till line end, regardless of anchor / cursor
## h                = to select till line start, regardless of anchor / cursor
## s                = to select till first non blank character, regardles of anchor / cursor
## g                = to select till start of file, regardless of anchor / cursor
## e                = to select till end of file, regardless of anchor / cursor
## X                = to select till line bounds
## https://github.com/helix-editor/helix/pull/1570
####################################################################################################
[keys.normal.G]
"l"                 = ["collapse_selection", "extend_to_line_end"]
"h"                 = ["collapse_selection", "extend_to_line_start"]
"s"                 = ["collapse_selection", "extend_to_first_nonwhitespace"]
"g"                 = ["collapse_selection", "select_mode", "goto_file_start", "exit_select_mode"]
"e"                 = ["collapse_selection", "select_mode", "goto_file_end", "exit_select_mode"]
"X"                 = "extend_to_line_bounds"


[editor]
cursorline          = true
cursorcolumn        = true
line-number         = "relative"
mouse               = true
bufferline          = "always"
color-modes         = true
completion-timeout  = 5 ## instantly render completions
popup-border        = "all" ## make popups look a bit tidy

[editor.lsp]
# display-messages    = true ## annoying to see all those messages
display-inlay-hints = true

[editor.cursor-shape]
insert              = "bar" ## visually distinguish between insert / normal mode
select              = "hidden" ## you don't actually need a cursor shape in select / visual mode

[editor.auto-pairs]
'('                 = ')'
'{'                 = '}'
'['                 = ']'
'"'                 = '"'
'`'                 = '`'
# '<'                 = '>' ## this was messing up conditional expressions

[editor.indent-guides]
render              = true
character           = "▏"  ## Some characters that work well: "▏", "┆", "┊", "⸽", "╎"
skip-levels         = 1

[editor.soft-wrap]
enable              = true

[editor.statusline]
mode.normal         = "NORMAL"
mode.insert         = "INSERT"
mode.select         = "SELECT"
left                = ["mode", "file-base-name", "file-modification-indicator", "read-only-indicator"]
center              = ["spinner", "file-name", "total-line-numbers", "separator", "position", "separator", "position-percentage", "spacer", "separator", "version-control"]
right               = ["file-encoding", "diagnostics", "separator", "selections", "separator", "file-line-ending", "separator", "file-type"]
separator           = "▏"


## <001>
## to delete from cursor position till end of line use <t (cr)>
## to delete from cursor position till begining of line use <T (cr)>
## this has some inherent flaws however, it works for me in most of the scenarios
## ref:
##   https://www.reddit.com/r/HelixEditor/comments/11alw7q/delete_to_end_of_line/
##   https://github.com/helix-editor/helix/issues/1630
