"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭─](fg:blue)\
$os\
$username\
$directory\
$git_branch\
$git_status\
$golang\
$lua\
$python\
$rust\
$fill\
$time\
$cmd_duration
[╰─$shlvl$character](fg:blue)"""

palette = 'everforest'

[character]
success_symbol = "[❯](blue)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](blue)"

[palettes.everforest]
bg_dim = "#232a2e"
bg0 = "#2d353b"
bg1 = "#343f44"
bg2 = "#3d484d"
bg3 = "#475258"
bg4 = "#4f585e"
bg5 = "#56635f"
bg_visual = "#543a48"
bg_red = "#514045"
bg_green = "#425047"
bg_blue = "#3a515d"
bg_yellow = "#4d4c43"
fg = "#d3c6aa"
red = "#e67e80"
orange = "#e69875"
yellow = "#dbbc7f"
green = "#a7c080"
aqua = "#83c092"
blue = "#7fbbb3"
purple = "#d699b6"
grey0 = "#7a8478"
grey1 = "#859289"
grey2 = "#9da9a0"
statusline1 = "#a7c080"
statusline2 = "#d3c6aa"
statusline3 = "#e67e80"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[os]
disabled = false
style = "fg:blue"
format = '[$symbol ]($style)'

[username]
show_always = true
style_user = "fg:aqua"
style_root = "fg:red"
format = '[$user ]($style)'

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = ""
"Developer" = "󰲋"
"dotfiles" = ""

[directory]
read_only = ""
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true
style = "fg:italic yellow"
format = "[ $path ]($style)"

[git_branch]
style = "fg:italic red"
format = '[on $symbol$branch ]($style)'

[git_status]
style = "fg:italic red"
format = '([\[$all_status$ahead_behind\] ]($style))'

[golang]
symbol = ""
style = "fg:blue"
format = '[via $symbol ($version) ]($style)'

[lua]
symbol = ""
style = "fg:blue"
format = '[via $symbol ($version) ]($style)'
version_format = "v${raw}"

[python]
symbol = ""
style = "fg:blue"
format = '[via $symbol ($version) (\($virtualenv\) )]($style)'
version_format = "v${raw}"

[rust]
symbol = ""
style = "fg:orange"
format = '[via $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:grey2"
format = '[ $time ]($style)'

[fill]
symbol = ' '

[cmd_duration]
min_time = 500
show_milliseconds = false
disabled = false
style = "italic red"

[shlvl]
disabled = false
symbol = "󰨊"
style = "italic red"
format = '[ $symbol─($shlvl) ]($style)'
