"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#3D484D)\
$os\
[](fg:#3D484D bg:#D3C6AA)\
[](fg:#D3C6AA bg:yellow)\
$directory\
[](fg:yellow bg:#b3c891)\
[](fg:#b3c891 bg:green)\
$git_branch\ 
$git_status\
[](fg:green bg:#9DA9A0)\
[](fg:#9DA9A0 bg:#859289)\
$time\
[ ](fg:#859289)\
$golang\
$lua\
$python\
$rust\
$cmd_duration\
[$shlvl$character](bold #D3C6AA)"""

palette = 'everforest_dark'

[character]
disabled = false
success_symbol = "[❯](bold fg:#D3C6AA)"
error_symbol = "[❯](bold fg:#E67E80)"
vimcmd_symbol = "[❮](bold fg:#7FBBB3)"
vimcmd_replace_one_symbol = "[❮](bold fg:#D699B6)"
vimcmd_replace_symbol = "[❮](bold fg:#D699B6)"
vimcmd_visual_symbol = "[❮](bold fg:yellow)"

[os]
disabled = false
style = "fg:bold #D3C6AA bg:#3D484D"
format = '[$symbol ]($style)'

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "fg:#1E2326 bg:#E67E80"
style_root = "fg:#1E2326 bg:#E67E80"
format = '[ $user ]($style)'

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = ""
"Developer" = "󰲋"
"dotfiles" = ""

[directory]
read_only = " "
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true
style = "bg:yellow fg:bold italic #1E2326"
format = "[  $path ]($style)"

[git_branch]
symbol = ""
style = "fg:bold italic #1E2326 bg:green"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:bold italic #1E2326 bg:green"
format = '([\[$all_status$ahead_behind\] ]($style))'

[golang]
symbol = ""
style = "fg:bold #7FBBB3"
format = '[$symbol ($version) ]($style)'

[lua]
symbol = "" 
style = "fg:bold yellow"
format = '[$symbol ($version) ]($style)'
version_format = "${raw}"

[python]
symbol = ""
style = "fg:bold #7FBBB3"
format = '[$symbol ($version)(\($virtualenv\)) ]($style)'
version_format = "v${raw}"

[rust]
symbol = ""
style = "fg:bold #E69875"
format = '[$symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:#1E2326 bg:#859289"
format = '[  $time ]($style)'

[cmd_duration]
disabled = false
show_milliseconds = false
show_notifications = true
min_time_to_notify = 45000
min_time = 5000
style = "bold italic #E67E80"
format = "[took $duration ]($style)"

[shlvl]
disabled = false
symbol = "󰨊"
style = "bold italic #E67E80"
format = '[$symbol-($shlvl) ]($style)'

[line_break]
disabled = true

[fill]
symbol = ' '

[palettes.everforest_dark]
yellow = "#DBBC7F"
green = "#A7C080"