"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](textdawn)\
$os\
[](fg:textdawn bg:rose)\
[](fg:rose bg:rosemoon)\
$directory\
[](fg:rosemoon bg:#f5c2e7)\
[](fg:#f5c2e7 bg:lovemoon)\
$git_branch\
$git_status\
[](fg:lovemoon bg:iris)\
[](fg:iris bg:textdawn)\
$time\
[ ](fg:textdawn)\
$golang\
$lua\
$python\
$rust\
$cmd_duration\
[$shlvl$character](bold text)"""

palette = 'rose_pine_mix'

[character]
disabled = false
success_symbol = "[❯](bold fg:text)"
error_symbol = "[❯](bold fg:love)"
vimcmd_symbol = "[❮](bold fg:pine)"
vimcmd_replace_one_symbol = "[❮](bold fg:iris)"
vimcmd_replace_symbol = "[❮](bold fg:iris)"
vimcmd_visual_symbol = "[❮](bold fg:gold)"

[os]
disabled = false
style = "fg:bold text bg:textdawn"
format = '[$symbol ]($style)'

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "fg:text bg:textdawn"
style_root = "fg:text bg:textdawn"
format = '[ $user ]($style)'

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = ""
"Developer" = "󰲋"
"dotfiles" = ""

[directory]
read_only = " "
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true
style = "bg:rosemoon fg:bold italic overlay"
format = "[  $path ]($style)"

[git_branch]
symbol = ""
style = "fg:bold italic overlay bg:love"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:bold italic overlay bg:love"
format = '([\[$all_status$ahead_behind\] ]($style))'

[golang]
symbol = ""
style = "fg:bold foam"
format = '[$symbol ($version) ]($style)'

[lua]
symbol = "" 
style = "fg:bold rose"
format = '[$symbol ($version) ]($style)'
version_format = "${raw}"

[python]
symbol = ""
style = "fg:bold foam"
format = '[$symbol ($version)(\($virtualenv\)) ]($style)'
version_format = "v${raw}"

[rust]
symbol = ""
style = "fg:bold love"
format = '[$symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:text bg:textdawn"
format = '[  $time ]($style)'

[cmd_duration]
disabled = false
show_milliseconds = false
show_notifications = true
min_time_to_notify = 45000
min_time = 5000
style = "bold italic love"
format = "[took $duration ]($style)"

[shlvl]
disabled = false
symbol = "󰨊"
style = "bold italic love"
format = '[$symbol-($shlvl) ]($style)'

[line_break]
disabled = true

[fill]
symbol = ' '

[palettes.rose_pine]
base = "#191724"
surface = "#1f1d2e"
overlay = "#26233a"
muted = "#6e6a86"
subtle = "#908caa"
text = "#e0def4"
love = "#eb6f92"
gold = "#f6c177"
rose = "#ebbcba"
pine = "#31748f"
foam = "#9ccfd8"
iris = "#c4a7e7"
highlight_low = "#21202e"
highlight_med = "#403d52"
highlight_high = "#524f67"	

[palettes.rose_pine_moon]
base = "#232136"
surface = "#2a273f"	
overlay = "#393552"	
muted = "#6e6a86"	
subtle = "#908caa"	
text = "#e0def4"	
love = "#eb6f92"	
gold = "#f6c177"	
rose = "#ea9a97"	
pine = "#3e8fb0"	
foam = "#9ccfd8"	
iris = "#c4a7e7"	
highlight_low = "#2a283e"	
highlight_med = "#44415a"	
highlight_high = "#56526e"

[palettes.rose_pine_dawn]
base = "#faf4ed"	
surface = "#fffaf3"	
overlay = "#f2e9e1"	
muted = "#9893a5"	
subtle = "#797593"	
text = "#575279"	
love = "#b4637a"	
gold = "#ea9d34"	
rose = "#d7827e"	
pine = "#286983"	
foam = "#56949f"	
iris = "#907aa9"	
highlight_low = "#f4ede8"	
highlight_med = "#dfdad9"	
highlight_high = "#cecacd"

[palettes.rose_pine_mix]
love = "#eb6f92"
lovemoon = "#eb6f92"
lovedawn = "#b4637a"
rose = "#ebbcba"
rosemoon = "#ea9a97"
rosedawn = "#d7827e"
base = "#232136"
basedawn = "#faf4ed"	
surface = "#1f1d2e"
surfacedawn = "#fffaf3"	
overlay = "#26233a"
overlaydawn = "#f2e9e1"
muted = "#6e6a86"
muteddawn = "#9893a5"
subtle = "#908caa"
subtlemoon = "#908caa"
subtledawn = "#797593"
text = "#e0def4"
textdawn = "#575279"
gold = "#f6c177"
golddawn = "#ea9d34"	
pine = "#31748f"
pinedawn = "#286983"
foam = "#9ccfd8"
iris = "#c4a7e7"
irisdawn = "#907aa9"
highlight_low = "#21202e"
highlight_med = "#403d52"
highlight_high = "#524f67"
highlight_highdawn = "#cecacd"