
format = '''
[┌  ](bold white)$directory$python$rust$package$git_branch$git_status$fill$time$cmd_duration
[│](bold white)
[└$shlvl─❯ ](bold white)'''

[directory]
read_only = " "
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true
style = "bold white underline"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
".dotfiles" = ""

[python]
symbol = ""
style = "bold #A599E9"
format = 'via[ $symbol ($version) (\($virtualenv\) )]($style)'
version_format = "v${raw}"

[rust]
symbol = ""
style = "bold #A599E9"
format = 'via[ $symbol ($version) ]($style)'

[package]
symbol = ""
style = "bold #B362FF"
format = 'is[ $symbol $version ]($style)'

[git_branch]
symbol = ""
style = "bold italic white"
format = 'on[ $symbol $branch ]($style)'

[git_status]
style = "bold italic #f7768e"
format = '[($all_status$ahead_behind )]($style)'

[fill]
symbol = ' '

[cmd_duration]
min_time = 500
show_milliseconds = false
disabled = false
style = "bold italic #f7768e"

[time]
disabled = false
time_format = "%R"
style = "bold #565f89"
format = '[ $time ]($style)'

[shlvl]
disabled = false
symbol = "󰨊"
style = "bold italic #ff9e64"
format = '[ $symbol ($shlvl) ]($style)'