"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭─](bold text)\
$os\
[](textdawn)\
$username\
[](fg:textdawn bg:rose)\
[](fg:rose bg:rosemoon)\
$directory\
[](fg:rosemoon bg:#f5c2e7)\
[](fg:#f5c2e7 bg:lovemoon)\
$git_branch\
$git_status\
[](fg:lovemoon bg:iris)\
[](fg:iris bg:textdawn)\
$time\
[ ](fg:textdawn)\
$cmd_duration\
$fill\
$golang\
$lua\
$python\
$rust
[╰─$shlvl─$character](bold text)"""

palette = 'rose_pine'

[character]
success_symbol = "[❯](text)"
error_symbol = "[❯](love)"
vimcmd_symbol = "[❮](pine)"

[palettes.rose_pine]
love = "#eb6f92"
lovemoon = "#eb6f92"
lovedawn = "#b4637a"
rose = "#ebbcba"
rosemoon = "#ea9a97"
rosedawn = "#d7827e"
base = "#232136"
surface = "#1f1d2e"
overlay = "#26233a"
overlaydawn = "#f2e9e1"
muted = "#6e6a86"
muteddawn = "#9893a5"
subtle = "#908caa"
subtlemoon = "#908caa"
subtledawn = "#797593"
text = "#e0def4"
textdawn = "#575279"
gold = "#f6c177"
pine = "#31748f"
pinedawn = "#286983"
foam = "#9ccfd8"
iris = "#c4a7e7"
irisdawn = "#907aa9"
highlight_low = "#21202e"
highlight_med = "#403d52"
highlight_high = "#524f67"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[os]
disabled = false
style = "fg:bold text"
format = '[$symbol ]($style)'

[username]
show_always = true
style_user = "fg:text bg:textdawn"
style_root = "fg:text bg:textdawn"
format = '[ $user ]($style)'

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Developer" = "󰲋 "
"dotfiles" = ""

[directory]
read_only = " "
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true
style = "bg:rosemoon fg:bold italic overlay"
format = "[ $path ]($style)"

[git_branch]
symbol = ""
style = "fg:bold italic overlay bg:love"
format = '[ on $symbol $branch ]($style)'

[git_status]
style = "fg:bold italic overlay bg:love"
format = '([\[$all_status$ahead_behind\] ]($style))'

[time]
disabled = false
time_format = "%R"
style = "fg:text bg:textdawn"
format = '[  $time ]($style)'

[cmd_duration]
min_time = 500
show_milliseconds = false
disabled = false
style = "bold italic love"

[fill]
symbol = ' '

[golang]
symbol = ""
style = "fg:bold rose"
format = '[ via $symbol ($version) ]($style)'

[lua]
symbol = "" 
style = "fg:bold rose"
format = '[ via $symbol ($version) ]($style)'
version_format = "${raw}"

[python]
symbol = ""
style = "fg:bold rose"
format = '[ via $symbol ($version) (\($virtualenv\)) ]($style)'
version_format = "v${raw}"

[rust]
symbol = ""
style = "fg:bold rose"
format = '[ via $symbol ($version) ]($style)'

[shlvl]
disabled = false
symbol = "󰨊"
style = "bold italic love"
format = '[ $symbol ($shlvl) ]($style)'
